/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args){
        Restaurant macRestaurant=new Restaurant("mac",5,"$");
        System.out.println(macRestaurant.toString());

        Review review1=new Review("areej",5,"very good ");
        Review review2=new Review("Yahya",4," good ");
        Review review3=new Review("yasmeen",5,"very good ");


        macRestaurant.addReview(review1);
        macRestaurant.addReview(review2);
        macRestaurant.addReview(review3);


        System.out.println(macRestaurant.viewReview());
    }
}
